---
title: "data-dictionary"
output: github_document
---

**team_name**: Name of the team (character)  

**game_date**: Date on which a game was played (character)  

**season**: Year of the basketball season (integer)  

**period**: An NBA game is divided in 4 periods of 12 mins each. For example, a value for period = 1 refers to the first period (the first 12 mins of the game) (integer)  

**minutes_remaining**: Amount of time, in minutes, that remained to be played in a given period (integer)  

**seconds_remaining**: Amount of time, in seconds, that remained to be played in a given period (integer)  

**shot_made_flag**: Indicates whether a shot was made (shot_yes) or missed (shot_n) (character)  

**action_type**: Has to do with the basketball moves used by players, either to pass by defenders to gain access to the basket, or to get a clean pass to a teammate to score a two pointer or three pointer (character)  

**shot_type**: Indicates whether a shot is a 2-point field goal (2), or a 3-point field goal (3) (integer)  

**shot_distance**: distance to the basket (measured in feet) (integer)  

**opponent**: Name of the opposing team (character)  

**x**: Refers to the court x coordinate (measured in inches) where a shot occurred (integer)  

**y**: Refers to the court y coordinate (measured in inches) where a shot occurred (integer)

**name**: Refers to the name of the player (character)

**minute**: Refers to the minute number when a shot occurred (integer)

